<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * JobAbstract
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobAbstract extends EntityRepository
{
}
