<?php

namespace AppBundle\Entity;
namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends EntityRepository
{
	public function findAllProjects()
    {
        $query = $this->getEntityManager()
        	->createQuery(
            	'SELECT p FROM AppBundle:Project p'
        	);

    	try {
        	return $query->getResult();
    	} catch (\Doctrine\ORM\NoResultException $e) {
        	return null;
    	}
    }

    public function findAll()
    {
        $users = $this->getEntityManager()
        ->createQueryBuilder()->select('u, i')
        ->from('AppBundle:Project', 'u')
        ->join('u.projectSkill', 'i')
        ->getQuery()->getResult();

        return $users;
    }

    public function findById($id)
    {
        $project = $this->getDoctrine()
        ->getRepository('AppBundle:Project')
        ->find($projectId);

        return $project;
    }
}
